# Generated by Django 4.1.7 on 2023-04-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0003_aboutpage_contactpage_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPage',
            new_name='ContactUsPage',
        ),
        migrations.AlterModelOptions(
            name='contactuspage',
            options={'verbose_name': 'contact_us_page'},
        ),
    ]
