# Generated by Django 4.1.7 on 2023-04-07 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('home', '0004_rename_contactpage_contactuspage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsPage',
            new_name='ContactPage',
        ),
        migrations.AlterModelOptions(
            name='contactpage',
            options={'verbose_name': 'contact_page'},
        ),
    ]
