# Generated by Django 4.1.8 on 2023-04-13 02:53

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('json', jsonfield.fields.JSONField(default='{}')),
                ('credit', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
                ('category', models.CharField(choices=[('', 'Select Category:'), ('CLOTHES', 'CLOTHES'), ('EQUIPMENT', 'EQUIPMENT'), ('ELECTRONICS', 'ELECTRONICS'), ('TOOLS', 'TOOLS'), ('MISC', 'MISC')], default='', max_length=15)),
                ('type', models.CharField(choices=[('PURCHASED', 'PURCHASED'), ('DONATION', 'DONATION'), ('OTHER', 'OTHER')], default='pur', max_length=10)),
                ('unitcost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('itemlimit', models.IntegerField()),
            ],
        ),
    ]
